---
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
  required:
    ':system_tests':
      - gem: beaker
        version: '~> 4'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.5'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 1.0'
      - gem: beaker-vmpooler
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 1.3'
    ':development':
      - gem: puppet-strings

Rakefile:
  changelog_version_tag_pattern: '%s'
  requires:
    - puppet-lint/tasks/puppet-lint

spec/spec_helper.rb:
  mock_with: ':rspec'
